[package]
name = "test_wmm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.20"
wkt = "0.10.3"
wmm = "0.2.3"
geo = "0.18"

